development:
  adapter: postgresql
  encoding: unicode
  database: codesolo_development
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: codesolo_production
  username: postgres
  password:
  # host: 1.1.1.1
  # port: 11

test:
  adapter: postgresql
  encoding: unicode
  database: codesolo_test
  username: postgres
  password:
